# Generated by Django 3.2.16 on 2023-01-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_rename_comments_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(default=2, max_length=254),
            preserve_default=False,
        ),
    ]
